version: "2.0"
services:
  db:
    image: postgres
    ports:
      - 5342:5342
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080

  dog-app:
    image: dog-app:0.0.2
    ports:
      - 8000:8000
