version: "2.0"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: example

  # Use postgres/example to login
  adminer:
    image: adminer
    ports:
      - 8080:8080
#  dog-app:
#    image: dog-app:0.0.2
#    ports:
#      - 8000:8000
